server:
   port: 8888

logging:
    path: logs
    file: userManager.log


spring:
   application:
          name: userManager
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://192.168.0.101:3307/course?serverTimezone=GMT
       username: root
       password: 123

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
